// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use the session/direct connection for migrations and Prisma CLI operations.
    // Fall back to DATABASE_URL for local environments that only define one URL.
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
